src/user-web/ft_transcendence/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chatRoomView, name="chat-window"),
    path("test/", views.chatRoomView, name="chat-room"),
]

src/user-web/ft_transcendence/ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenVerifyView

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("user/", include("user.urls")),
    path("game/", include("game.urls")),
    path("chat/", include("chat.urls")),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
]

src/user-web/ft_transcendence/game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path("", views.indexView, name="index"),
    path("pong/", views.pongRoomView, name="pong"),
    path("pong-local/", views.pongRoomLocalView, name="pong-local"),
    path("register/", views.registerGameView, name="register"),
]

src/user-web/ft_transcendence/user/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenVerifyView, TokenRefreshView

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logoutView, name="logout"),
    path("oauth-callback/", views.oauth_callback, name="oauth-callback"),
    path("get-oauth-url/", views.get_oauth_url, name="get-oauth-url"),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
    # path("refresh-token/", TokenRefreshView.as_view(), name='token_refresh'),
    path("refresh-token/", views.refreshTokenView.as_view(), name="token_refresh"),
    path("friend-request/<str:target_username>/", views.FriendRequestView.as_view(), name="friend-request"),
    path("block-request/<str:target_username>/", views.UserBlockView.as_view(), name="block-request"),
    path("two-factor/", views.TwoFactorAuthenticationView.as_view(), name="two-factor"),

    path("profile/", views.profileView, name="profile"),
    path("profile/<int:target_id>/", views.profileView, name="target-profile"),

    path("change-password/", views.passwordChangeView, name="change-password"),
    path("delete-account/", views.deleteUserView, name="delete-account"),
    path("add-two-factor/<int:type>/", views.TwoFactorSettingView.as_view(), name="add-two-factor"),
    path("remove-two-factor/", views.TwoFactorSettingView.as_view(), name="remove-two-factor"),
    path("get_image/<int:user_id>/", views.UserImageView.as_view(), name="get-user-image"),
    path("get_image/", views.UserImageView.as_view(), name="get-user-image-2"),
    # =================
    #  Views for debug
    # =================
    path("check-session/", views.check_session, name="check-session"),
    path("check/", views.checkuser, name="user-check"),
    path("check2/", views.checkuser2, name="user-check2"),
    path("check3/", views.checkuser3, name="user-check3"),
    path("check4/", views.checkuser4, name="user-check4"),
    path("dummy/", views.dummyscores, name="dummy-scores"),
]

src/user-web/ft_transcendence/game/models.py
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db.models import UniqueConstraint
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from datetime import timedelta

def max_player_validator(game_id):
    game = GameHistory.objects.get(pk=game_id)

    if game.player_count() >= game.max_players():
        raise ValidationError(_("Game #%(id)s is already full with maximum number of %(max)s players"),
                              params={"id": game_id, "max": game.max_players()})

def extract_query(history, target_user=None):
    games = list()

    for match in history:
        game = dict()
        
        game["id"] = match.pk
        game["date"] = match.date
        game["length"] = match.length
        game["type"] = GameHistory.GameType(match.type).name

        players = list()
        counter = 1

        for user in match.gamehistoryuser_set.all():
            player = dict()

            player["id"] = user.user.pk if user.user is not None else str("null")
            player["username"] = user.user.username if user.user is not None else str("[anonymous]")
            player["total_score"] = user.total_score
            player["wins"] = user.wins
            player["place"] = counter

            if target_user is not None and user.user is not None and user.user.pk == target_user:
                game["target_player"] = player

                if counter == 1:
                    game["target_player"]["has_won"] = True
                else:
                    game["target_player"]["has_won"] = False

            counter += 1
            players.append(player)

        game["players"] = players
        games.append(game)

    return games

class GameHistoryManager(models.Manager):

    def get_user_summary(self, user) -> dict:
        games = GameHistory.objects.prefetch_related('gamehistoryuser_set').filter(gamehistoryuser__user=user)

        onevsone = {'total': 0, 'wins': 0, 'losses': 0}
        tournament = {'total': 0, 'first': 0, 'second': 0, 'third': 0}

        for game in games:
            counter = 1
            for player in game.gamehistoryuser_set.all():
                if player.user == user:
                    if game.type == GameHistory.GameType.ONEVONE:
                        onevsone['total'] += 1
                        if counter == 1:
                            onevsone['wins'] += 1
                        else:
                            onevsone['losses'] += 1
                    else:
                        tournament['total'] += 1
                        if counter == 1:
                            tournament['first'] += 1
                        elif counter == 2:
                            tournament['second'] += 1
                        elif counter == 3:
                            tournament['third'] += 1
                counter += 1

        return {'onevsone': onevsone, 'tournament': tournament}

    def get_user_history(self, user_id, last=10):
        records = GameHistoryUser.objects.filter(user=user_id).order_by("-game__date")
        count = records.count()

        if last > count:
            records = records[0:count]
        else:
            records = records[0:last]

        return GameHistory.objects.filter(pk__in=records.values("game")).prefetch_related('gamehistoryuser_set')

    def get_user_best(self, user_id, last=3):
        records = GameHistoryUser.objects.filter(user=user_id).order_by("-wins", "-total_score")
        count = records.count()
        
        if last > count:
            records = records[0:count]
        else:
            records = records[0:last]

        return GameHistory.objects.filter(pk__in=records.values("game")).prefetch_related('gamehistoryuser_set')

    def get_ranking(self, last=10):
        records = GameHistoryUser.objects.order_by("-wins", "-total_score")
        count = records.count()

        if last > count:
            records = records[0:count]
        else:
            records = records[0:last]

        return GameHistory.objects.filter(pk__in=records.values("game")).prefetch_related('gamehistoryuser_set')

    def create_dummy_scores(self):
        if GameHistory.objects.count() != 0:
            return

        current_tz = timezone.get_current_timezone()
        
        self.game1 = GameHistory.objects.create(date=timezone.datetime(year=2010,
                                                                       month=1,
                                                                       day=1,
                                                                       tzinfo=current_tz),
                                                length=timedelta(minutes=5),
                                                type=GameHistory.GameType.ONEVONE)
        self.game2 = GameHistory.objects.create(date=timezone.now(),
                                                length=timedelta(seconds=30),
                                                type=GameHistory.GameType.TOURNAMENT)

        self.user1 = get_user_model().objects.create_user(username="user1", email="user1@mail.com", password="x")
        self.user2 = get_user_model().objects.create_user(username="user2", email="user2@mail.com", password="x")
        self.user3 = get_user_model().objects.create_user(username="user3", email="user3@mail.com", password="x")
        self.user4 = get_user_model().objects.create_user(username="user4", email="user4@mail.com", password="x")

        self.guser1_1 = GameHistoryUser.objects.create(game=self.game1, user=self.user1, total_score=25, wins=1)
        self.guser1_2 = GameHistoryUser.objects.create(game=self.game1, user=self.user2, total_score=10, wins=0)

        self.guser2_1 = GameHistoryUser.objects.create(game=self.game2, user=self.user1, total_score=200, wins=4)
        self.guser2_2 = GameHistoryUser.objects.create(game=self.game2, user=self.user2, total_score=185, wins=2)
        self.guser2_3 = GameHistoryUser.objects.create(game=self.game2, user=self.user3, total_score=32, wins=1)
        self.guser2_4 = GameHistoryUser.objects.create(game=self.game2, user=self.user4, total_score=50, wins=0)

        self.game3 = GameHistory.objects.create(date=timezone.now(),
                                                length=timedelta(hours=1),
                                                type=GameHistory.GameType.ONEVONE)
        self.game4 = GameHistory.objects.create(date=timezone.now(),
                                                length=timedelta(minutes=15),
                                                type=GameHistory.GameType.TOURNAMENT)

        GameHistoryUser.objects.create(game=self.game3, user=self.user1, total_score=15, wins=0)
        GameHistoryUser.objects.create(game=self.game4, user=self.user1, total_score=16, wins=1)
        GameHistoryUser.objects.create(game=self.game4, user=self.user2, total_score=17, wins=0)
        GameHistoryUser.objects.create(game=self.game4, user=self.user3, total_score=18, wins=0)

class GameHistory(models.Model):

    class Meta:
        verbose_name_plural = "game histories"
        ordering = ("-date",)

    class GameType(models.IntegerChoices):
        ONEVONE = 1, _("One vs One")
        TOURNAMENT = 2, _("Tournament")

        __empty__ = _("Unknown Game Type")

    type = models.IntegerField(choices=GameType)

    date = models.DateTimeField()
    length = models.DurationField()

    objects = GameHistoryManager()

    def player_count(self):
        return self.gamehistoryuser_set.count()

    def player_exists(self, user_id):
        return self.gamehistoryuser_set.filter(user=user_id).count() > 0

    def get_player_record(self, user_id):
        try:
            return self.gamehistoryuser_set.get(user=user_id)
        except ObjectDoesNotExist:
            return None

    def max_players(self):
        return 4 if self.type == self.GameType.TOURNAMENT else 2

class GameHistoryUser(models.Model):

    class Meta:
        constraints = [
            UniqueConstraint(fields=["game", "user"], name="history_user_index_constraint"),
        ]
        
        ordering = ("game", "-wins", "-total_score")

    game = models.ForeignKey(GameHistory, validators=[max_player_validator], on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    total_score = models.IntegerField()
    wins = models.IntegerField()

    def __str__(self):
        return self.user.username + "@" + str(self.game.type)

src/user-web/ft_transcendence/game/views.py
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.utils import timezone

from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from rest_framework.response import Response

from game import models

@api_view(['GET'])
def indexView(request):
	return render(request, 'game/index.html')

@api_view(['GET'])
def pongRoomView(request):
    return render(request, 'game/pong_room.html')

@api_view(['GET'])
def pongRoomLocalView(request):
    return render(request, 'game/pong_local.html')

@api_view(['POST'])
def registerGameView(request):
    data = JSONParser().parse(request)

    game = models.GameHistory.objects.create(type=data["game_type"],
                                               date=timezone.now(),
                                               length=timedelta(seconds=data["max_seconds"]),)

    for p in data["players"]:
        player = data["players"][p]
        user = get_user_model().objects.get(username=p)
        models.GameHistoryUser.objects.create(game=game,
                                                user=user,
                                                total_score=player["total_score"],
                                                wins=player["wins"])

    return Response({'message': 'Game data has been recorded'})

src/user-web/ft_transcendence/templates/game/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Game</title>
	{% load static %}
    <link rel="stylesheet" href="{% static 'global.css' %}" />
    <link rel="stylesheet" href="{% static 'nav.css' %}" />
     <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
	<script defer src="{% static 'spa.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg mx-auto navbar-custom mt-4">
      <div class="container-fluid">
        <a href="{% url 'index' %}" class="navbar-brand h1 mb-0">PONG</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-target="#navbarTogglerDemo01"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/chat/">Chat</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'game:index' %}">Tournament</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Ranking</a>
            </li>
            <li class="nav-item">
              <a
                href="{% url 'user:logout' %}"
                class="nav-link btn31 btn-danger custom-logout-button1"
                id="logoutButton"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div
      class="d-flex justify-content-center position-relative"
      style="height: 100vh"
    >
      <div
        class="position-absolute"
        style="
          left: 50%;
          top: 50%;
          transform: translate(-85%, -50%);
          border: 3px solid black;
          border-radius: 4px;
          box-shadow: 0 0 75px #fafafa;
        "
      >
        <canvas id="pongCanvas" width="800" height="400"></canvas>
      </div>
    </div>
  </body>
</html>

src/user-web/ft_transcendence/templates/game/pong_local.html
<div class="container-fluid">
    <div class="row">
        <div id="webgl" class="position-relative" tabindex="0">
            <div id="webgl-scoreboard" class="overflow-y-auto overflow-x-hidden position-absolute top-0 end-0
            p-2 bg-dark rounded border border-2 border-warning"
                style="height: 25vh; max-height: 25vh; width: 250px; max-width: 250px;">
                <div class="row justify-content-center text-center text-light">
                    <h5 class="fw-bolder">Scoreboard</h5>
                </div>
                <div class="row text-center text-white-50">
                    <div class="col">
                        <h6 class="fw-semibold">Players</h6>
                    </div>
                    <div class="col">
                        <h6 class="fw-semibold">Scores</h6>
                    </div>
                </div>
                <div class="row text-white-50 text-center">
                    <div class="col" id="local-pong-player-scores">
                        <!-- Scoreboard content goes here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1">
        <textarea class="col" id="pong-message-log" rows="18" readonly
            style='background-color:transparent !important;'></textarea>
    </div>
    <div class="row m-1 mx-auto">
        <div class="btn-group-vertical" role="group" aria-label="Vertical radio toggle button group">
            <input type="radio" class="btn-check" name="vbtn-radio" id="1v1-radio" autocomplete="off">
            <label class="btn btn-outline-warning" for="1v1-radio">1 V 1</label>
            <input type="radio" class="btn-check" name="vbtn-radio" id="tournament-radio" autocomplete="off">
            <label class="btn btn-outline-warning" for="tournament-radio">Tournament</label>

            <button type="button" class="btn btn-danger" id="lStartGame">Start Game</button>
        </div>
        <div class="text-bg-info mx-auto my-3 p-2 rounded text-center">
            <div>
                Each match starts by pressing X button, game can be paused by pressing T button.
            </div>
            <div>
                Player controls: player0 [W,S], player1 [ArrowUp, ArrowDown]
            </div>
        </div>
    </div>
</div>

{% include 'eoc.html' %}

src/user-web/ft_transcendence/templates/game/pong_room.html
<div class="container-fluid">
    <div class="row">
        <div id="webgl" class="position-relative" tabindex="0">
            <div id="webgl-scoreboard"
            class="overflow-y-auto overflow-x-hidden position-absolute top-0 end-0
            p-2 bg-dark rounded border border-2 border-warning"
            style="height: 25vh; max-height: 25vh; width: 250px; max-width: 250px;">
                <div class="row justify-content-center text-center text-light">
                    <h5 class="fw-bolder">Scoreboard</h5>
                </div>
                <div class="row text-center text-white-50">
                    <div class="col">
                        <h6 class="fw-semibold">Players</h6>
                    </div>
                    <div class="col">
                        <h6 class="fw-semibold">Scores</h6>
                    </div>
                </div>
                <div class="row text-white-50 text-center">
                    <div class="col" id="pong-player-scores">
                        <!-- Scoreboard content goes here -->
                        <div class="row">
                            <!-- First player -->
                            <div class="col">
                                mrOwner <span class="position-absolute start-50 text-warning"><i class="bi bi-star-fill"></i></span>
                            </div>
                            <div class="col">
                                <div class="row justify-content-between">
                                    <div class="col">1W</div>
                                    <div class="col">154P</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <!-- Second player -->
                            <div class="col">
                                Bazooka
                            </div>
                            <div class="col">
                                <div class="row justify-content-between">
                                    <div class="col">3W</div>
                                    <div class="col">527P</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1">
        <textarea
        class="col text-light text-opacity-75 bg-dark bg-opacity-25"
        id="pong-message-log"
        style="height:50vh;"
        readonly></textarea>
    </div>
    <div class="row m-1">
        <input class="col-10" id="pong-message-input" type="text" placeholder="Message">
        <input class="col-2 btn btn-info" id="pong-message-submit" type="button" value="Send">
    </div>
    <div class="row m-1">
        <input class="col-3" id="pong-room-input" type="text" placeholder="Room name">
        <input class="col-2 btn btn-success" id="pong-room-connect" type="button" value="Connect">
        <input class="col-2 btn btn-danger" id="pong-room-disconnect" type="button" value="Disconnect">
        <input class="col-2 btn btn-warning" id="pong-room-ready" type="button" value="Toggle Ready">
        <input class="col-1 ms-2" id="pong-room-move-up" type="button" value="↑" hidden>
        <input class="col-1" id="pong-room-move-down" type="button" value="↓" hidden>
        <input class="col btn btn-light" id="pong-room-switch-type" type="button" value="Switch Type">
    </div>
    <div class="row m-1">
        <textarea class="col" id="pong-ping-log" rows="20" readonly></textarea>
        <div class="bg-dark text-light col" id="pong-player1-log"></div>
        <div class="bg-dark text-light col" id="pong-player2-log"></div>
    </div>
</div>

{% include 'eoc.html' %}