src/user-web/ft_transcendence/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chatRoomView, name="chat-window"),
    path("test/", views.chatRoomView, name="chat-room"),
]

src/user-web/ft_transcendence/ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenVerifyView

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("user/", include("user.urls")),
    path("game/", include("game.urls")),
    path("chat/", include("chat.urls")),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
]

src/user-web/ft_transcendence/game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path("", views.indexView, name="index"),
    path("pong/", views.pongRoomView, name="pong"),
    path("pong-local/", views.pongRoomLocalView, name="pong-local"),
    path("register/", views.registerGameView, name="register"),
]

src/user-web/ft_transcendence/user/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenVerifyView, TokenRefreshView

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logoutView, name="logout"),
    path("oauth-callback/", views.oauth_callback, name="oauth-callback"),
    path("get-oauth-url/", views.get_oauth_url, name="get-oauth-url"),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
    # path("refresh-token/", TokenRefreshView.as_view(), name='token_refresh'),
    path("refresh-token/", views.refreshTokenView.as_view(), name="token_refresh"),
    path("friend-request/<str:target_username>/", views.FriendRequestView.as_view(), name="friend-request"),
    path("block-request/<str:target_username>/", views.UserBlockView.as_view(), name="block-request"),
    path("two-factor/", views.TwoFactorAuthenticationView.as_view(), name="two-factor"),

    path("profile/", views.profileView, name="profile"),
    path("profile/<int:target_id>/", views.profileView, name="target-profile"),

    path("change-password/", views.passwordChangeView, name="change-password"),
    path("delete-account/", views.deleteUserView, name="delete-account"),
    path("add-two-factor/<int:type>/", views.TwoFactorSettingView.as_view(), name="add-two-factor"),
    path("remove-two-factor/", views.TwoFactorSettingView.as_view(), name="remove-two-factor"),
    path("get_image/<int:user_id>/", views.UserImageView.as_view(), name="get-user-image"),
    path("get_image/", views.UserImageView.as_view(), name="get-user-image-2"),
    # =================
    #  Views for debug
    # =================
    path("check-session/", views.check_session, name="check-session"),
    path("check/", views.checkuser, name="user-check"),
    path("check2/", views.checkuser2, name="user-check2"),
    path("check3/", views.checkuser3, name="user-check3"),
    path("check4/", views.checkuser4, name="user-check4"),
    path("dummy/", views.dummyscores, name="dummy-scores"),
]

src/user-web/ft_transcendence/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Dashboard{% endblock %}</title>
    <meta name="author" content="bcayir, buyildir, gsepetci, hkok, tcakmako" />
    <meta
      name="description"
      content="{% block description %}Ecole 42 Ft_transcendence Project{% endblock %}"
    />
    <meta
      name="keywords"
      content="{% block keywords %}game, pingpong{% endblock %}"
    />
    {% load static %}

    <script type="importmap">
      {
        "imports": {
          "three": "{% static 'game/three.module.js' %}",
          "three-css2drenderer": "{% static 'game/CSS2DRenderer.js' %}"
        }
      }
    </script>

    <link
      rel="icon"
      type="image/x-icon"
      href="{% block favicon %}{% static '42_Logo.png' %}{% endblock %}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
    <link rel="stylesheet" href="{% static 'global.css' %}" />
    <link rel="stylesheet" href="{% static 'nav.css' %}" />
    <link rel="stylesheet" href="{% static 'error.css' %}" />
    <link rel="stylesheet" href="{% static 'chat/chat.css' %}" />
    <link rel="stylesheet" href="{% static 'chat/json-highlight.css' %}"/>

    <script defer src="{% static 'game/pong_room.js' %}"></script>
    <script defer src="{% static 'chat/chat_room.js' %}"></script>

    <script defer type="module" src="{% static 'game/three-pong.js' %}"></script>
    <script defer type="module" src="{% static 'game/three-pong-local.js' %}"></script>
    <script defer src="{% static 'game/LocalPongGameLogic.js' %}"></script>

    <script defer src="{% static 'cookieHandler.js' %}"></script>
    <script defer src="{% static 'user/sessionNavigator.js' %}"></script>
    <script defer src="{% static 'fetchWithJWT.js' %}"></script>
    <script defer src="{% static 'binders.js' %}"></script>
    <script defer src="{% static 'spa.js' %}"></script>
    <script defer src="{% static 'user/submitForm.js' %}"></script>
    <script defer src="{% static 'user/profile.js' %}"></script>
    
    <script defer src="{% static 'home/online_status.js' %}"></script>

  </head>
  <body>
    <div id="content">
      {% block content %}Hello World! This is base.html{% endblock %}
    </div>

    <div id="toast-content" class="toast-container position-fixed bottom-0 end-0 p-3">
    </div>
  </body>
</html>

src/user-web/ft_transcendence/templates/eoc.html
<div class="eoc"></div> <!-- end of content -->

src/user-web/ft_transcendence/templates/error.html
<div class="col-lg-6 justify-content-center">
    <div class="text-center shadow error-wrapper">
        <div class="error-icon">
            <i class="bi bi-exclamation-triangle error"></i>
        </div>
        <p class="error-text pb-5">
            {{ error }}
        </p>
    </div>
</div>

src/user-web/ft_transcendence/templates/home.html
{% if user.is_authenticated %}
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100">
        <div class="col-md-4 col-xl-3 chat">
            <div class="card contacts-card">
                <div class="card-header">
                    <h4 class="text-light fw-light my-1">
                        Friends
                    </h4>
                </div>
                <div class="card-body px-3 contacts_body">
                    <ul id="home-friend-list" class="contacts">
                        {% for friend_user in friends %}
                        <li id="home-friend-list-item-{{ friend_user.username }}">
                            <div class="d-flex bd-highlight">
                                <div class="img_cont">
                                    <img src="{% url 'user:get-user-image' user_id=friend_user.id %}" class="rounded-circle user_img">
                                    <span class="online_icon"></span>
                                </div>
                                <div class="user_info">
                                    <a
                                    class="link-light link-underline link-underline-opacity-0"
                                    href="{% url 'user:target-profile' target_id=friend_user.id %}">
                                        {{ friend_user.username }}
                                    </a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xl-6 chat">
            <div class="card contacts-card">
                <div class="card-header msg_head">
                    <h4 class="fw-light text-light my-1">
                        Friend Requests
                    </h4>
                </div>
                <div class="card-body overflow-x-hidden overflow-y-auto">
                    {% if incoming|length > 0 %}
                    <ul class="list-group list-group-flush text-end">
                        {% for pending_user in incoming %}
                        <li class="list-group-item text-light bg-transparent">
                            <a
                            class="link-info link-underline link-underline-opacity-0"
                            href="{% url 'user:target-profile' target_id=pending_user.id %}">
                                {{ pending_user.username }}
                            </a>
                            has sent you a friend request.
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <span>You have no incoming friend requests.</span>
                    {% endif %}
                </div>
            </div>
        </div>
	</div>
</div>
{% else %}
<div class="text-center">
    <h1 class="display-3 white-glow light-text-gradient mb-5">Welcome to Transcendence</h1>
</div>

<div style="max-width:65%;">
    <div style="position:relative; width:100%; height:0px; padding-bottom:56.175%">
        <iframe
        class="shadow-lg"
        allow="fullscreen;autoplay" allowfullscreen="" height="100%"
        src="https://streamable.com/e/paag0y?autoplay=1&amp;muted=1&amp;nocontrols=1"
        width="100%"
        style="width:100%; height:100%; position:absolute; left:0px; top:0px; overflow:hidden; webkit-border-radius: 20px;-moz-border-radius: 20px;border-radius: 20px;">
        </iframe>
    </div>
</div>

{% endif %}
<div class="text-center">
    <button
    class="btn btn-light m-5 shadow"
    id="dummyButton"
    onclick="fetch('{% url 'user:dummy-scores' %}', {method: 'PUT'}); return false;">
        Create Dummies
    </button>
</div>

{% include 'eoc.html' %}

src/user-web/ft_transcendence/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}

{% include 'navbar.html' %}

<div class="container-lg">
  {% if messages %}
  <div class="row p-1">
    {% include 'messages_dismissible.html' %}
  </div>
  {% endif %}
  <div class="row p-3 justify-content-center overflow-auto" style="min-height:70vh;" id="main-content">

  
  
  </div>
</div>

{% endblock %}

src/user-web/ft_transcendence/templates/messages.html
{% if messages %}
{% for message in messages %}
    <div role="alert" class="alert
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert-warning
    {% else %}alert-info
    {% endif %}
    ">
        {{ message }}
    </div>
{% endfor %}
{% endif %}

src/user-web/ft_transcendence/templates/messages_dismissible.html
{% if messages %}
{% for message in messages %}
{% if message.tags %}
    <div  role="alert" class="alert alert-dismissible fade show pe-1 ps-3 py-2
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert-warning
    {% else %}alert-info{% endif %}">{{ message }}
    <button type="button" class="btn close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
{% endif %}
{% endfor %}
{% endif %}

src/user-web/ft_transcendence/templates/navbar.html
<div>
  <div class="container-lg">
    <nav class="navbar navbar-expand-lg navbar-custom2 shadow navbar-dark my-4">
      <div class="container-fluid">
        <a href="/" class="navbar-brand h1 mb-0">TRANSCENDENCE</a>
        <button
          class="navbar-toggler ms-auto"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarContent"
          aria-controls="navbarContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-between"
          id="navbarContent"
        >
          <ul class="navbar-nav text-center mx-auto pe-lg-4">
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'game:pong' %}" class="nav-link">Pong</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'game:pong-local' %}" class="nav-link">L-Pong</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'chat:chat-room' %}" class="nav-link">ChatRoom</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'user:profile' %}" class="nav-link" id="navProfileButton" hidden>Profile</a>
            </li>

          </ul>
          <ul class="navbar-nav ms-lg-5 ps-lg-5">
            <!-- Dinamik olarak giriş yapmış kullanıcılara gösterilecek çıkış butonu -->
            <li class="nav-item">
              <a
                href="{% url 'user:logout' %}"
                class="nav-link btn btn-dark btn-logout shadow-sm" id="navLogoutButton" hidden
                >Logout</a
              >
            </li>
            <!-- Dinamik olarak giriş yapmamış kullanıcılara gösterilecek giriş yap butonu -->
            <li class="nav-item">
              <a
                href="{% url 'user:login' %}"
                class="nav-link btn btn-dark shadow-sm" id="navLoginButton"
                >Login</a
              >
            </li>
          </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>