src/user-web/ft_transcendence/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chatRoomView, name="chat-window"),
    path("test/", views.chatRoomView, name="chat-room"),
]

src/user-web/ft_transcendence/ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenVerifyView

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("user/", include("user.urls")),
    path("game/", include("game.urls")),
    path("chat/", include("chat.urls")),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
]

src/user-web/ft_transcendence/user/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenVerifyView, TokenRefreshView

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logoutView, name="logout"),
    path("oauth-callback/", views.oauth_callback, name="oauth-callback"),
    path("get-oauth-url/", views.get_oauth_url, name="get-oauth-url"),
    path("verify-token/", TokenVerifyView.as_view(), name="token_verify"),
    # path("refresh-token/", TokenRefreshView.as_view(), name='token_refresh'),
    path("refresh-token/", views.refreshTokenView.as_view(), name="token_refresh"),
    path("friend-request/<str:target_username>/", views.FriendRequestView.as_view(), name="friend-request"),
    path("block-request/<str:target_username>/", views.UserBlockView.as_view(), name="block-request"),
    path("two-factor/", views.TwoFactorAuthenticationView.as_view(), name="two-factor"),

    path("profile/", views.profileView, name="profile"),
    path("profile/<int:target_id>/", views.profileView, name="target-profile"),

    path("change-password/", views.passwordChangeView, name="change-password"),
    path("delete-account/", views.deleteUserView, name="delete-account"),
    path("add-two-factor/<int:type>/", views.TwoFactorSettingView.as_view(), name="add-two-factor"),
    path("remove-two-factor/", views.TwoFactorSettingView.as_view(), name="remove-two-factor"),
    path("get_image/<int:user_id>/", views.UserImageView.as_view(), name="get-user-image"),
    path("get_image/", views.UserImageView.as_view(), name="get-user-image-2"),
    # =================
    #  Views for debug
    # =================
    path("check-session/", views.check_session, name="check-session"),
    path("check/", views.checkuser, name="user-check"),
    path("check2/", views.checkuser2, name="user-check2"),
    path("check3/", views.checkuser3, name="user-check3"),
    path("check4/", views.checkuser4, name="user-check4"),
    path("dummy/", views.dummyscores, name="dummy-scores"),
]

src/user-web/ft_transcendence/user/forms.py
from django.contrib.auth.forms import BaseUserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import gettext_lazy as _

class UserLoginForm(forms.Form):
    username = forms.CharField(label=_("Username"), max_length=20, widget=forms.TextInput())
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

class UserPasswordChangeForm(forms.Form):
    old_password = forms.CharField(label=_("Old Password"), max_length=20, widget=forms.PasswordInput())
    new_password1 = forms.CharField(label=_("New Password 1"), max_length=20, widget=forms.PasswordInput())
    new_password2 = forms.CharField(label=_("New Password 2"), max_length=20, widget=forms.PasswordInput())

class UserRegistrationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()
        fields = BaseUserCreationForm.Meta.fields + ("email",)

src/user-web/ft_transcendence/user/views.py
from django.http import JsonResponse, HttpResponse, Http404, FileResponse

from django.db.models import Q
from django.contrib.auth import logout, authenticate, login, get_user_model
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect, reverse
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.files.images import ImageFile

from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework.views import APIView
from rest_framework import status

from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.serializers import TokenRefreshSerializer
from django_otp.forms import OTPTokenForm
from django_otp.plugins.otp_email.models import EmailDevice

import json
import logging # is this necessary?
import requests # is this necessary?
import os
from tempfile import NamedTemporaryFile

from . import forms
from . import serializers
from user.models import UserRelationship
from game.models import GameHistory, extract_query

TOKEN_URL = "https://api.intra.42.fr/oauth/token"
AUTHORIZATION_URL = "https://api.intra.42.fr/oauth/authorize"

logger = logging.getLogger(__name__)

class RegisterView(APIView):

    def get(self, request):
        context = {'form': forms.UserRegistrationForm().render("user/form_snippet.html")}
        return render(request, "user/register.html", context)

    def post(self, request):

        data = json.loads(request.body)
        form = forms.UserRegistrationForm(data=data)

        if form.is_valid():
            try:
                user = form.save()
            except ValueError as e:
                return Response({'success': False, "message": "ValueError", "errors": e.args}, status=400)
            except:
                return Response({'success': False, "message": _("An error occured while registering user in the database")},
                                    status=507)
            return Response({'success': True, "redirect": reverse("user:login"), "message": _("Successfully registered")})

        else:
            password1 = form.data.get("password1", None)
            password2 = form.data.get("password2", None)
            username = form.data.get("username", None)
            email = form.data.get("email", None)

            errors = []

            for error in form.errors:
                if form.data.get(error, None) is None:
                    errors.append(_(error + " field is not found"))
                elif error == 'email':
                    if get_user_model().objects.filter(email=email).exists():
                        errors.append(_("Email is already taken"))
                    else:
                        errors.append(_("Invalid email"))
                elif error == 'password2' and password1 == password2:
                    errors.append(_("The password is not strong enough"))
                elif error == 'password2' and password1 != password2:
                    errors.append(_("The passwords do not match"))
                elif error == 'username':
                    if get_user_model().objects.filter(username=username).exists():
                        errors.append(_("Username is already taken"))
                    else:
                        errors.append(_("Invalid username" + error))
                else:
                    errors.append(_("Invalid form error: " + error))
            return Response({'success': False, 'errors': errors}, status=401)

class LoginView(APIView):
    def get(self, request):
        if not request.user.is_authenticated:
            form = forms.UserLoginForm().render("user/form_snippet.html")
            return render(request, "user/login.html", {'form': form})
        else:
            return HttpResponseRedirect(reverse("home"))

    def post(self, request):
        data = JSONParser().parse(request)
        serializer = serializers.UserLoginSerializer(data=data)

        if serializer.is_valid():
            username = serializer.validated_data['username']
            password = serializer.validated_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                if user.two_fa_auth_type == get_user_model().TwoFAType.NONE:
                    refresh = RefreshToken.for_user(user)
                    response_data = {'success': True,
                                     'redirect': reverse('home'),
                                     'message': _("login successful"),
                                     }
                    response = Response(response_data)
                    response.set_cookie('refresh_token', str(refresh), secure=True, samesite='Strict', httponly=True)
                    response.set_cookie('access_token', str(refresh.access_token), secure=True, samesite='Strict')
                    response.set_cookie('username', str(username), secure=True, samesite='Strict')
                    return response
                else:
                    request.session["attempting_user"] = user.id
                    response = {'success': True,
                                'redirect': reverse('user:two-factor'),
                                'message': _("Login successful")}
                    return Response(response)
            else:
                response = {'success': False, 'errors': [_("Incorrect username or password")]}
                return Response(response, status=status.HTTP_401_UNAUTHORIZED)
        else:
            # for error in serializer.errors:
            #    messages.error(request, "Invalid Serializer:" + error)
            response = {'success': False, 'errors': serializer.errors}
            return Response(response, status=status.HTTP_401_UNAUTHORIZED)

@api_view(['GET'])
def logoutView(request):
    if request.session.get("attempting_user", None) is not None:
        request.session.pop("attempting_user")
    response = Response({'success': True, 'redirect': reverse('home'),
                         'message': _("User is logged out")})
    response.delete_cookie('refresh_token', samesite='Strict')
    response.delete_cookie('access_token', samesite='Strict')
    response.delete_cookie('username', samesite='Strict')
    return response

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def profileView(request, target_id = None):

    if target_id is None:
        user = request.user
    else:
        user = get_object_or_404(get_user_model(), id=target_id)

    history = extract_query(GameHistory.objects.get_user_history(user.pk), user.pk)
    relationship = UserRelationship.objects.get_type(request.user, user)
    summary = GameHistory.objects.get_user_summary(user)
    context = {"target_user" : user, "ranking": history,
               "relationship": relationship, "summary": summary}
    return render(request, "user/profile.html", context)


class refreshTokenView(APIView):
    def post(self, request):
        data = JSONParser().parse(request)
        serializer = TokenRefreshSerializer(data=data)

        if serializer.is_valid():
            access = serializer.validated_data['access']
            response = Response({'success': True, 'message': _("Refreshed access token")})
            response.set_cookie('access_token', access, secure=True, samesite='Strict')
            return response
        else:
            if request.session.get("attempting_user", None) is not None:
                request.session.pop("attempting_user")
            response = Response({'success': False, 'errors': [_("Invalid refresh token")]},
                                status=status.HTTP_401_UNAUTHORIZED)
            response.delete_cookie('refresh_token', samesite='Strict')
            response.delete_cookie('access_token', samesite='Strict')
            response.delete_cookie('username', samesite='Strict')
            return response
    def get(self, request):
        refresh_token = request.COOKIES.get("refresh_token")
        if refresh_token is None:
            return Response({'success': False,
                             'errors': [_("Refresh token not found in cookies")]},
                            status=status.HTTP_400_BAD_REQUEST)

        serializer = TokenRefreshSerializer(data={"refresh": refresh_token})

        if serializer.is_valid():
            access = serializer.validated_data['access']
            response = Response({'success': True, 'message': _("Refreshed access token")})
            response.set_cookie('access_token', access, secure=True, samesite='Strict')
            return response
        else:
            response = Response({'success': False, 'errors': [_("Invalid refresh token")]},
                                status=status.HTTP_401_UNAUTHORIZED)
            response.delete_cookie('refresh_token', samesite='Strict')
            response.delete_cookie('access_token', samesite='Strict')
            response.delete_cookie('username', samesite='Strict')
            return response

def get_oauth_url(request):
    oauth_url = f"{AUTHORIZATION_URL}?client_id={settings.OAUTH_CLIENT_ID}&redirect_uri={settings.OAUTH_REDIRECT_URI}&response_type=code"
    return JsonResponse({'oauth_url': oauth_url, 'redirect': reverse('home')})

@api_view(['GET', 'POST'])
def oauth_callback(request):
    code = request.GET.get('code')
    if code:
        token_response = requests.post(TOKEN_URL, data={
            'grant_type': 'authorization_code',
            'client_id': settings.OAUTH_CLIENT_ID,

src/user-web/ft_transcendence/templates/user/login.html
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-xl-6">
      <div class="card p-4 bg-transparent" id="loginCard">
        <div class="card-body">
          <form action="{% url 'user:login' %}" method="POST" id="login-form">
            <h2 class="mb-5">Login</h2>
            {% csrf_token %}
			{{ form }}
            <button
              type="submit"
              class="btn btn-full btn-dark mb-4"
              id="loginSubmitButton"
            >
              Login
            </button>
          </form>

          {% include 'messages.html' %}

          <div class="sign-link31 m-0">
            <p>
              Don't have an account?
              <a
                href="{% url 'user:register' %}"
                class="register-link31"
                id="registerLink"
              >
                Register
              </a>
            </p>
            <p>
              Test
              <a
                href="{% url 'user:two-factor' %}"
                class="register-link31"
                id="2FALink"
              >
                2FA Auth
              </a>
            </p>
          </div>
          {% load static %}
          <div class="text-center">
            <img
              src="{% static '42_Logo.png' %}"
              alt="OAuth Login"
              class="oauth-logo"
              style="cursor: pointer"
              id="42LoginLink"
            />
          </div>
          <div id="form_error"></div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'eoc.html' %}

src/user-web/ft_transcendence/templates/user/register.html
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-xl-6">
      <div class="card p-4 bg-transparent" id="registerCard">
        <div class="card-body">
          <form action="{% url 'user:register' %}" method="POST" id="register-form">
            <h2 class="mb-5">Register</h2>
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-full btn-dark mb-4" id="registerSubmitButton">
              Register
            </button>
          </form>
          
          {% include 'messages.html' %}

          <div class="sign-link31 m-0">
            <p>
              You have already an account?
              <a href="{% url 'user:login' %}" class="register-link31" id="loginLink">Sign in</a>
            </p>
          </div>
          <div id="form_error"></div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'eoc.html' %}

src/user-web/ft_transcendence/templates/user/two-factor.html
<div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="card p-4 bg-transparent" id="2faCard">
          <div class="card-body">
            <form action="{% url 'user:two-factor' %}" method="POST" id="2fa-form">
              <h2 class="mb-5">Two Factor Authentication</h2>
              {% csrf_token %}
              {{ form }}
              <button type="submit" class="btn btn-full btn-dark mb-4" id="2FASubmitButton">
                Submit
              </button>
            </form>
            
            {% include 'messages.html' %}
  
            <div class="sign-link31 m-0">
            </div>
            <div id="form_error"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% include 'eoc.html' %}